### ISSUE TITLE
Location Based Alerting Demo (geohash version)

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/ksqldb-recipes#114]
**Describe the use case**
https://github.com/confluentinc/apac-workshops/tree/d134877b5587bdfc842c7231abbb96fa92e30420/marketing-locationbased-geohash

Show real time, personalized location based alerts in real time. User and merchant data from a database is joined against real time user locations (e.g. from mobile devices) to provide alerts when users pass within 200 meters of a participating merchant.  User locations are subdivided by geohash and users receive an alert if they come within 200m of any participating merchant (the red circle).

**Provide the ksqlDB application**
Document the full set of ksqlDB statements that represent the use case.

https://github.com/confluentinc/apac-workshops/blob/master/marketing-locationbased-geohash/ksql-statements.sql

**Comment by rspurgeon** [comment]
This example uses a UDF (named `GEO_HASH`, source not included in the example repository) as part of its logic to determine the proximity of two geo locations (IIUC). As Cloud ksqlDB does not support UDFs, I'm not sure how to build the recipe for this example at this time as a cloud only application.  cc @MichaelDrogalis @ybyzek @kaijunxu

**Comment by kaijunxu** [comment]
The UDF comes from https://github.com/wlaforest/KSQLGeo/blob/master/src/main/java/com/github/wlaforest/ksql/udf/GeoHashUDF.java which in turn uses https://github.com/locationtech/spatial4j/blob/master/src/main/java/org/locationtech/spatial4j/io/GeohashUtils.java#L62-L116. For ksqlDB in CC, I've had to directly include geohash in the source data because UDFs are not available.

As an additional note: using the geohash in this manner would cause "missed" matches for users who are within the 200m circle but outside the geohash - this can be seen for the two southern locations in the example map. I've had interesting discussions with users around mitigations e.g. checking adjacent geohashes, tweaking geohash precision and so on but that could be a "bonus credit" part of the recipe.

**Comment by rspurgeon** [comment]
@kaijunxu thank you. Any chance you can provide some example Geohash data here to make part of the recipe? Also, do you have a sample solution already in mind for the substring match against the hashes that you could share?

**Comment by kaijunxu** [comment]
Sample data (merchants)
`{"id": 1, "latitude": 14.54866069, "longitude": 121.04772111, "description": "7-Eleven RCBC Center", "geohash":"wdw4f8820"},
{"id": 2, "latitude": 14.54733288, "longitude": 121.05161762, "description": "7-Eleven South of Market", "geohash":"wdw4f8707"},
{"id": 3, "latitude": 14.55296667, "longitude": 121.05167165, "description": "Lawson Eco Tower", "geohash":"wdw4f971h"},`

Sample data (user locations)
Matches merchant 1:  `{"GEOHASH": "wdw4f820h17", "lat": 14.547279, "lon": 121.04754}`
Matches merchant 2: `{"GEOHASH": "wdw4f8e8237", "lat": 14.548695, "lon": 121.052185}`
Matches merchant 3: `{"GEOHASH": "wdw4f9560bu", "lat": 14.55174, "lon": 121.051865}`
No match example: `{"GEOHASH": "wdw4f8vbp6y", "lat": 14.550034, "lon": 121.05558}`

Sample solution:

Modifications to https://github.com/confluentinc/apac-workshops/blob/master/marketing-locationbased-geohash/ksql-statements.sql#L18-L33
'CREATE TABLE merchant_locations
WITH (KAFKA_TOPIC='merchant_locations', FORMAT='JSON_SR')
AS SELECT ROWKEY->id AS id,
  LATEST_BY_OFFSET(after->description, false) AS description,
  CAST(LATEST_BY_OFFSET(after->latitude, false) AS DECIMAL(10,7)) AS latitude,
  CAST(LATEST_BY_OFFSET(after->longitude, false) AS DECIMAL(10,7)) AS longitude,
  LATEST_BY_OFFSET(after->geohash, false) AS geohash
FROM merchant_locations_raw
GROUP BY ROWKEY->id;

CREATE TABLE merchant_lookups
WITH (KAFKA_TOPIC='merchant_lookups', FORMAT='JSON_SR')
AS SELECT SUBSTRING(geohash, 1, 6) AS geohash,
  COLLECT_LIST(id) as idlist
FROM merchant_locations
WHERE description IS NOT null
GROUP BY SUBSTRING(geohash, 1, 6);'

Modifications to https://github.com/confluentinc/apac-workshops/blob/master/marketing-locationbased-geohash/ksql-statements.sql#L48-L58
`CREATE STREAM alerts_raw
WITH (KAFKA_TOPIC='alerts_raw', VALUE_FORMAT='JSON_SR')
AS SELECT userloc.userid as userid,
 userloc.latitude AS latitude,
 userloc.longitude AS longitude,
 userloc.timestamp AS timestamp,
 SUBSTRING(userloc.geohash,1 , 6) AS geohash,
 EXPLODE(merchantloc.idlist) AS merchantid
FROM user_locations userloc
LEFT JOIN merchant_lookups merchantloc ON SUBSTRING(userloc.geohash, 1, 6) = merchantloc.geohash
PARTITION BY null;`

Otherwise, solution in https://github.com/confluentinc/apac-workshops/blob/master/marketing-locationbased-geohash/ksql-statements.sql remains unchanged.

**Comment by rspurgeon** [comment]
@kaijunxu thank you for the detailed clarification and modified code !

**Comment by rspurgeon** [comment]
@kaijunxu Thanks for this information here.  I'm trying to figure out the difference in our queries where we join on matching geo-hashes, but then we also filter based on the result of the `GEO_DISTANCE` function.  Maybe i'm not understanding, but does joining on a subset of the hash serve the same function as filtering on the geo distance, or does `GEO_DISTANCE` further refine the distance calculation where the geohash is something like an "initial match"?

**Comment by kaijunxu** [comment]
@rspurgeon It is the latter - the geohash is used to create the "initial match/alert candidates" which are then run by the `GEO_DISTANCE` calculation. If we had customer locations distributed evenly across the [entire demo area](https://github.com/confluentinc/apac-workshops/blob/master/marketing-locationbased-geohash/locations-map2.jpg), this lets us only do the distance calculation for half of the users (instead of all of them) per merchant location. At a state or national level, this could save quite a bit of compute especially if there are multiple merchants in each geohash.

Admittedly, the sample merchant locations are not ideal in the sense that the merchant locations and their 200m diameter circles are not entirely contained in a single geohash. This is expected in real-life though, and is a compromise between query complexity/compute resources/potential missed alerts etc. that the business would have to consider.
